Downgrade nixpkgs because of MacOS build error
It seems https://github.com/NixOS/nixpkgs/pull/287609 caused the following
build error for us on MacOS:

```
error:
       … while evaluating a branch condition

         at /nix/store/hxvhrj46m6j9m1x2z4qa4s1r4gw18sqv-source/pkgs/stdenv/booter.nix:99:7:

           98|     thisStage =
           99|       if args.__raw or false
             |       ^
          100|       then args'

       … in the right operand of the update (//) operator

         at /nix/store/hxvhrj46m6j9m1x2z4qa4s1r4gw18sqv-source/pkgs/stdenv/booter.nix:84:7:

           83|       { allowCustomOverrides = index == 1; }
           84|       // (stageFun prevStage))
             |       ^
           85|     (lib.lists.reverseList stageFuns);

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: value is a function while a set was expected
```

We should look into if this is an issue in nixpkgs or in our MacOS
environment (GitHub).

This commit changes the following Nix versions:

  * 2.21.2 -> 2.21.0
  * 2.20.6 -> 2.20.5
  * 2.19.4 -> 2.19.3
  * 2.3.18 -> 2.3.17